# Generated by Django 3.2.20 on 2023-10-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20231010_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotes',
            name='daily_employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
