# Generated by Django 4.1.3 on 2022-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_jobs_id_jobs_contract_status_and_more'),
    ]
