# Generated by Django 4.1.3 on 2022-11-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_remove_jobs_job_number_jobs_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs2',
            fields=[
                ('job_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=250, null=True)),
                ('estimator', models.CharField(max_length=50, null=True)),
                ('foreman', models.CharField(max_length=50, null=True)),
                ('superintendent', models.CharField(max_length=50, null=True)),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('po_number', models.CharField(max_length=50, null=True)),
                ('retainage_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_t_m_job', models.BooleanField(default=False)),
                ('t_m_nte_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('booked_date', models.DateTimeField(blank=True, null=True)),
                ('booked_by', models.CharField(max_length=50, null=True)),
                ('is_wage_scale', models.BooleanField(default=False)),
                ('is_davis_bacon_wages', models.BooleanField(default=False)),
                ('spray_scale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brush_role', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('estimate_number', models.CharField(max_length=50, null=True)),
                ('estimate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_wallcovering', models.BooleanField(default=False)),
                ('has_owner_supplied_wallcovering', models.BooleanField(default=False)),
                ('painting_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wallcovering_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_send_auto_co_emails', models.BooleanField(default=False)),
                ('is_send_auto_submittal_emails', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('approved_change_orers', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('final_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('labor_done_Date', models.DateTimeField(blank=True, null=True)),
                ('ar_closed_date', models.DateTimeField(blank=True, null=True)),
                ('was_previously_closed', models.BooleanField(default=False)),
                ('previously_closed_date', models.DateTimeField(blank=True, null=True)),
                ('cumulative_costs_at_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('contract_status', models.BooleanField(default=False)),
                ('insurance_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_number',
            field=models.CharField(default=1, max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
