# Generated by Django 4.1.3 on 2022-11-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_jobs2_remove_jobs_id_jobs_job_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
