# Generated by Django 4.1.3 on 2022-11-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_delete_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs2',
            new_name='Jobs',
        ),
    ]
