# Generated by Django 4.1.3 on 2022-12-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_rename_jobs2_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='job_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
            preserve_default=False,
        ),
    ]
