# Generated by Django 4.1.3 on 2022-12-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_alter_inventory_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='superintendent',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='superintendent_email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='superintendent_phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
