# Generated by Django 4.1.3 on 2022-12-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_remove_clients_superintendent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_information',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='tm_prices',
            name='job_id',
        ),
        migrations.AddField(
            model_name='client_information',
            name='job_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='job_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
            preserve_default=False,
        ),
    ]
