# Generated by Django 4.1.3 on 2022-12-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_remove_client_information_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
