# Generated by Django 4.1.3 on 2022-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_alter_employees_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='has_paint',
            field=models.BooleanField(default=False),
        ),
    ]
