# Generated by Django 4.1.3 on 2022-12-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_jobs_has_paint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Notes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobs')),
            ],
        ),
    ]
