# Generated by Django 4.1.3 on 2022-12-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_job_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='submittals_required',
            field=models.BooleanField(default=False),
        ),
    ]
