# Generated by Django 4.1.3 on 2022-12-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_alter_clients_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcovering',
            name='test',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
