# Generated by Django 4.1.3 on 2022-12-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_wallcovering_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
