# Generated by Django 4.1.3 on 2022-12-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_alter_clients_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallcovering',
            name='test',
        ),
        migrations.AddField(
            model_name='clients',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
