# Generated by Django 4.1.3 on 2022-12-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0024_clients_id'),
    ]


