# Generated by Django 4.1.3 on 2022-12-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0027_alter_clients_id'),
    ]



