# Generated by Django 4.1.3 on 2022-12-02 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0030_alter_clients_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
