# Generated by Django 4.1.3 on 2022-12-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0031_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=250, null=True)),
                ('estimator', models.CharField(max_length=250, null=True)),
                ('estimator_phone', models.CharField(max_length=50, null=True)),
                ('estimator_email', models.CharField(max_length=250, null=True)),
                ('bid_fax', models.CharField(max_length=50, null=True)),
                ('bid_email', models.CharField(max_length=50, null=True)),
                ('vendor_code', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
