# Generated by Django 4.1.3 on 2022-12-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0032_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_notes',
            name='daily_employee_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job_notes',
            name='note_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
