# Generated by Django 4.1.3 on 2022-12-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0033_job_notes_daily_employee_count_job_notes_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
