# Generated by Django 4.1.3 on 2022-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0034_jobs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='approved_change_orers',
            new_name='approved_change_orders',
        ),
        migrations.AddField(
            model_name='jobs',
            name='has_special_paint',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
