# Generated by Django 4.1.3 on 2022-12-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0036_job_numbers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_Numbers',
        ),
    ]
