# Generated by Django 4.1.3 on 2022-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0037_delete_job_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('number', models.IntegerField(max_length=4)),
            ],
        ),
    ]
