# Generated by Django 4.1.3 on 2022-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0038_job_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_numbers',
            name='number',
            field=models.IntegerField(),
        ),
    ]
