# Generated by Django 4.1.3 on 2022-12-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0039_alter_job_numbers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_numbers',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
