# Generated by Django 4.1.3 on 2022-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0040_alter_job_numbers_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='contract_status',
            field=models.IntegerField(),
        ),
    ]
