# Generated by Django 4.1.3 on 2022-12-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0043_jobs_client_jobs_client_co_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_on_base',
            field=models.BooleanField(default=False),
        ),
    ]
