# Generated by Django 4.1.3 on 2022-12-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0044_jobs_is_on_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='estimator',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='estimator_email',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='estimator_phone',
        ),
        migrations.AddField(
            model_name='clients',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Client_Employees',
            fields=[
                ('person_PK', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.clients')),
            ],
        ),
    ]
