# Generated by Django 4.1.3 on 2022-12-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0045_remove_clients_estimator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_employees',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
