# Generated by Django 4.1.3 on 2022-12-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0046_client_employees_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
