# Generated by Django 4.1.3 on 2022-12-04 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0048_jobs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='client_Co_Contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CO', to='console.client_employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Pm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PM', to='console.client_employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Submittal_Contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Submittals', to='console.client_employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Super',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Super', to='console.client_employees'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='superintendent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.employees'),
        ),
    ]
