# Generated by Django 4.1.3 on 2022-12-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0049_alter_jobs_client_co_contact_alter_jobs_client_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='superintendent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.employees'),
        ),
    ]
