# Generated by Django 4.1.3 on 2022-12-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0051_alter_jobs_painting_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='t_m_nte_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
