# Generated by Django 4.1.3 on 2022-12-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0052_alter_jobs_t_m_nte_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='approved_change_orders',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='brush_role',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='estimate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='final_bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='retainage_percentage',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='spray_scale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='t_m_nte_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
