# Generated by Django 4.1.3 on 2022-12-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0053_alter_jobs_approved_change_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='superintendent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.employees'),
        ),
    ]
