# Generated by Django 4.1.3 on 2022-12-05 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0054_alter_jobs_superintendent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='client_Co_Contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CO', to='console.client_employees'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PM', to='console.client_employees'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Submittal_Contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Submittals', to='console.client_employees'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Super',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Super', to='console.client_employees'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='has_special_paint',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='insurance_status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_send_auto_co_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_send_auto_submittal_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='submittals_required',
            field=models.IntegerField(null=True),
        ),
    ]
