# Generated by Django 4.1.3 on 2022-12-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0055_alter_jobs_client_co_contact_alter_jobs_client_pm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='job_name',
        ),
    ]
