# Generated by Django 4.1.3 on 2022-12-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0056_remove_inventory_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.inventory_type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='job_number',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='po_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchased_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='storage_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
