# Generated by Django 4.1.3 on 2022-12-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0057_inventory_status_alter_inventory_inventory_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
