# Generated by Django 4.1.3 on 2022-12-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0059_alter_inventory_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=250, null=True)),
                ('company_phone', models.CharField(max_length=20, null=True)),
                ('company_email', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.vendor_category')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=250, null=True)),
                ('purchase_order', models.CharField(max_length=250, null=True)),
                ('on_rent_date', models.DateTimeField(blank=True, null=True)),
                ('off_rent_date', models.DateTimeField(blank=True, null=True)),
                ('off_rent_number', models.CharField(max_length=250, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.vendors')),
                ('job_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.jobs')),
            ],
        ),
    ]
