# Generated by Django 4.1.3 on 2022-12-05 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0060_vendor_category_vendors_vendor_contact_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='job_name',
        ),
        migrations.AddField(
            model_name='jobs',
            name='assigned_inventory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='assigned_rentals',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='unsigned_tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='change_orders',
            name='job_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extra_work_tickets',
            name='job_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incoming_wall_covering',
            name='job_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
            preserve_default=False,
        ),
    ]
