# Generated by Django 4.1.3 on 2022-12-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0061_remove_checklist_job_name_jobs_assigned_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=250, null=True)),
                ('purchase_order', models.CharField(max_length=250, null=True)),
                ('on_rent_date', models.DateTimeField(blank=True, null=True)),
                ('off_rent_date', models.DateTimeField(blank=True, null=True)),
                ('off_rent_number', models.CharField(max_length=250, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.vendors')),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobs')),
            ],
        ),
        migrations.AlterField(
            model_name='submittal_items',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='submittals',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
