# Generated by Django 4.1.3 on 2022-12-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0062_rentals_alter_submittal_items_job_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='assigned_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='assigned_rentals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='unsigned_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
