# Generated by Django 4.1.3 on 2022-12-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0063_alter_jobs_assigned_inventory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_Users',
        ),
    ]
