# Generated by Django 4.1.3 on 2022-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0064_delete_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_orders',
            name='ewt_number',
        ),
        migrations.RemoveField(
            model_name='change_orders',
            name='is_waiting_for_pm',
        ),
        migrations.AddField(
            model_name='change_orders',
            name='is_ticket_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='change_orders',
            name='ticket_processing',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='change_orders',
            name='gc_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='change_orders',
            name='is_t_and_m',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Extra_Work_Tickets',
        ),
    ]
