# Generated by Django 4.1.3 on 2022-12-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0065_remove_change_orders_ewt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_orders',
            name='closed',
        ),
    ]
