# Generated by Django 4.1.3 on 2022-12-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0066_remove_change_orders_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_orders',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
