# Generated by Django 4.1.3 on 2022-12-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0070_subcontract_items_subcontracts_delete_subcontract_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client_Information',
        ),
    ]
