# Generated by Django 4.1.3 on 2022-12-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0071_delete_client_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='TM_Prices_Master',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supervisor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('painter_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('painter_hours_ot', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('painter_hours_premium_only', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('inventory_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bond_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material1', models.CharField(max_length=50, null=True)),
                ('price1', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material2', models.CharField(max_length=50, null=True)),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material3', models.CharField(max_length=50, null=True)),
                ('price3', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material4', models.CharField(max_length=50, null=True)),
                ('price4', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material5', models.CharField(max_length=50, null=True)),
                ('price5', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material6', models.CharField(max_length=50, null=True)),
                ('price6', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material7', models.CharField(max_length=50, null=True)),
                ('price7', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material8', models.CharField(max_length=50, null=True)),
                ('price8', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material9', models.CharField(max_length=50, null=True)),
                ('price9', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material10', models.CharField(max_length=50, null=True)),
                ('price10', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material11', models.CharField(max_length=50, null=True)),
                ('price11', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material12', models.CharField(max_length=50, null=True)),
                ('price12', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('material13', models.CharField(max_length=50, null=True)),
                ('price13', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tm_prices',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material10',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material11',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material12',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material13',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material7',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material8',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='material9',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='price9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tm_prices',
            name='supervisor_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tm_prices',
            name='painter_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tm_prices',
            name='painter_hours_ot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tm_prices',
            name='painter_hours_premium_only',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
