# Generated by Django 4.1.3 on 2022-12-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0072_tm_prices_master_remove_tm_prices_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tm_list',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='tm_list',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='tm_list',
            name='paint_type',
        ),
        migrations.RemoveField(
            model_name='tm_list',
            name='tm_price_id',
        ),
        migrations.AddField(
            model_name='change_orders',
            name='date_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tm_list',
            name='change_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.change_orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tm_list',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tm_list',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='tm_list',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tm_list',
            name='units',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
