# Generated by Django 4.1.3 on 2022-12-05 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0073_remove_tm_list_amount_remove_tm_list_job_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallcovering',
            old_name='description',
            new_name='pattern',
        ),
        migrations.AlterField(
            model_name='wallcovering',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='wallcovering',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.vendors'),
        ),
    ]
