# Generated by Django 4.1.3 on 2022-12-05 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0074_rename_description_wallcovering_pattern_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='is_closed',
            new_name='is_received',
        ),
        migrations.RenameField(
            model_name='wallcovering',
            old_name='width',
            new_name='roll_width',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='wallcovering_id',
        ),
        migrations.RemoveField(
            model_name='wallcovering',
            name='estimated',
        ),
        migrations.RemoveField(
            model_name='wallcovering',
            name='price',
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='estimated_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='estimated_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='is_random_reverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='is_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing1_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing1_yards_tier1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing2_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing2_yards_tier1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='pricing3_yards_tier1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='job_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.vendors'),
        ),
        migrations.CreateModel(
            name='Order_Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_description', models.CharField(max_length=100, null=True)),
                ('item_notes', models.CharField(max_length=1000, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('wallcovering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.wallcovering')),
            ],
        ),
    ]
