# Generated by Django 4.1.3 on 2022-12-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0075_rename_is_closed_orders_is_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='orders_primary_key',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='package_description',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='package_primary_key',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='incoming_wall_covering',
            name='wallcovering_primary_key',
        ),
    ]
