# Generated by Django 4.1.3 on 2022-12-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0077_outgoing_item_wallcovering_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittal_items',
            name='cop_primary_key',
        ),
        migrations.RemoveField(
            model_name='submittal_items',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='submittal_items',
            name='job_number',
        ),
        migrations.RemoveField(
            model_name='submittals',
            name='wallcovering_id',
        ),
        migrations.AddField(
            model_name='submittal_items',
            name='submittal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.submittals'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittals',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submittal_items',
            name='wallcovering_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.wallcovering'),
        ),
    ]
