# Generated by Django 4.1.3 on 2022-12-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0079_remove_subcontract_items_sov_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoing_wallcovering',
            name='date',
        ),
        migrations.RemoveField(
            model_name='subcontracts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallcovering_delivery',
            name='date',
        ),
    ]
