# Generated by Django 4.1.3 on 2022-12-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0080_remove_outgoing_wallcovering_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing_wallcovering',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcontracts',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering_delivery',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
