# Generated by Django 4.1.3 on 2022-12-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0081_outgoing_wallcovering_date_subcontracts_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='company_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
