# Generated by Django 4.1.3 on 2022-12-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0082_alter_vendors_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentals',
            name='off_rent_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
