# Generated by Django 4.1.3 on 2022-12-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0085_subcontractors_email_subcontractors_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractors',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subcontractors',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
