# Generated by Django 4.1.3 on 2022-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0086_alter_subcontractors_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallcovering',
            name='cut_charge',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wallcovering',
            name='roll_width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallcovering',
            name='vertical_repeat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
