# Generated by Django 4.1.3 on 2022-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0087_alter_wallcovering_cut_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallcovering',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
