# Generated by Django 4.1.3 on 2022-12-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0089_remove_subcontract_items_sov_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontract_items',
            name='SOV_is_lump_sum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subcontract_items',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subcontract_items',
            name='notes',
            field=models.CharField(blank=True, max_length=2050, null=True),
        ),
    ]
