# Generated by Django 4.1.3 on 2022-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0090_subcontract_items_sov_is_lump_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='po_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
