# Generated by Django 4.1.3 on 2022-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0091_alter_orders_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
