# Generated by Django 4.1.3 on 2022-12-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0092_alter_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='item_notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
