# Generated by Django 4.1.3 on 2022-12-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0093_alter_order_items_item_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittals',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
