# Generated by Django 4.1.3 on 2022-12-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0096_remove_change_orders_ticket_processing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change_orders',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
