# Generated by Django 4.1.3 on 2022-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0097_alter_change_orders_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='is_bonded',
            field=models.BooleanField(default=False),
        ),
    ]
