# Generated by Django 4.1.3 on 2022-12-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0099_remove_tm_prices_bond_percentage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TM_Prices',
        ),
    ]
