# Generated by Django 4.1.3 on 2022-12-11 15:06

import console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0100_delete_tm_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm_list',
            name='category',
            field=models.CharField(max_length=50, validators=[console.models.validate_tm_category]),
        ),
        migrations.AlterField(
            model_name='tm_prices_master',
            name='category',
            field=models.CharField(max_length=50, validators=[console.models.validate_tm_category]),
        ),
    ]
