# Generated by Django 4.1.3 on 2022-12-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0101_alter_tm_list_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to='console.clients'),
            preserve_default=False,
        ),
    ]
