# Generated by Django 4.1.3 on 2022-12-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0102_alter_jobs_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='id',
        ),
    ]
