# Generated by Django 4.1.3 on 2022-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0104_alter_jobs_booked_by_alter_jobs_client_co_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_orders',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
