# Generated by Django 4.1.3 on 2022-12-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0106_remove_wallcovering_delivery_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='job_number',
        ),
    ]
