# Generated by Django 4.1.3 on 2022-12-11 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0108_remove_packages_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='wallcovering_delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.orders'),
        ),
    ]
