# Generated by Django 4.1.3 on 2022-12-11 23:28

import console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0109_alter_orders_job_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMPricesMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, validators=[console.models.validate_tm_category])),
                ('item', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RenameModel(
            old_name='Change_Orders',
            new_name='ChangeOrders',
        ),
        migrations.RenameModel(
            old_name='Client_Employees',
            new_name='ClientEmployees',
        ),
        migrations.RenameModel(
            old_name='Inventory_Type',
            new_name='InventoryType',
        ),
        migrations.RenameModel(
            old_name='Job_Notes',
            new_name='JobNotes',
        ),
        migrations.RenameModel(
            old_name='Job_Numbers',
            new_name='JobNumbers',
        ),
        migrations.RenameModel(
            old_name='Order_Items',
            new_name='OrderItems',
        ),
        migrations.RenameModel(
            old_name='Outgoing_Item',
            new_name='OutgoingItem',
        ),
        migrations.RenameModel(
            old_name='Outgoing_Wallcovering',
            new_name='OutgoingWallcovering',
        ),
        migrations.RenameModel(
            old_name='Storage_Location_Type',
            new_name='StorageLocationType',
        ),
        migrations.RenameModel(
            old_name='Subcontract_Items',
            new_name='SubcontractItems',
        ),
        migrations.RenameModel(
            old_name='Submittal_Items',
            new_name='SubmittalItems',
        ),
        migrations.RenameModel(
            old_name='TM_List',
            new_name='TMList',
        ),
        migrations.RenameModel(
            old_name='Vendor_Category',
            new_name='VendorCategory',
        ),
        migrations.RenameModel(
            old_name='Vendor_Contact',
            new_name='VendorContact',
        ),
        migrations.RenameModel(
            old_name='Wallcovering_Delivery',
            new_name='WallcoveringDelivery',
        ),
        migrations.DeleteModel(
            name='TM_Prices_Master',
        ),
        migrations.RenameField(
            model_name='clientemployees',
            old_name='person_PK',
            new_name='person_pk',
        ),
    ]
