# Generated by Django 4.1.3 on 2022-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0111_alter_changeorders_date_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='bid_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='client_estimator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='estimates',
            name='send_bids_to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Co_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Pm_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Submittal_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='client_Super_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='subcontractors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
