# Generated by Django 4.1.3 on 2022-12-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0114_alter_orderitems_wallcovering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallcoveringdelivery',
            name='items',
        ),
    ]
