# Generated by Django 4.1.3 on 2022-12-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0115_remove_wallcoveringdelivery_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='unit_item1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='unit_item2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='unit_item3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='unit_item4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='unit_item5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
