# Generated by Django 4.1.3 on 2022-12-15 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0117_rename_po_number_subcontracts_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrderNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('cop_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.changeorders')),
            ],
        ),
    ]
