# Generated by Django 4.1.3 on 2022-12-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0118_changeordernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='date_week_ending',
            field=models.DateField(blank=True, null=True),
        ),
    ]
