# Generated by Django 4.1.3 on 2022-12-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0122_painterhours_friday_painterhours_monday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painterhours',
            old_name='overtime',
            new_name='is_overtime',
        ),
    ]
