# Generated by Django 4.1.3 on 2022-12-18 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0123_rename_overtime_painterhours_is_overtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('category', models.CharField(max_length=2000, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventory')),
            ],
        ),
    ]
