# Generated by Django 4.1.3 on 2022-12-19 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0124_inventorynotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='console.vendors'),
            preserve_default=False,
        ),
    ]
