# Generated by Django 4.1.3 on 2022-12-19 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0125_inventory_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='job_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs'),
        ),
    ]
