# Generated by Django 4.1.3 on 2022-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0126_alter_inventory_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorynotes',
            name='job_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='inventorynotes',
            name='job_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='inventorynotes',
            name='service_vendor',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
