# Generated by Django 4.1.3 on 2022-12-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0127_inventorynotes_job_name_inventorynotes_job_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorynotes',
            name='service_vendor',
        ),
    ]
