# Generated by Django 4.1.3 on 2022-12-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0129_alter_inventory_vendor_alter_inventorynotes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='is_all_delivered_to_job',
            field=models.BooleanField(default=False),
        ),
    ]
