# Generated by Django 4.1.3 on 2022-12-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0132_remove_wallcovering_pricing1_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcoveringpricing',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='wallcoveringpricing',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
