# Generated by Django 4.1.3 on 2022-12-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0134_remove_packages_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
