# Generated by Django 4.1.3 on 2022-12-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0135_orderitems_is_satisfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_satisfied',
        ),
    ]
