# Generated by Django 4.1.3 on 2022-12-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0137_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcovering',
            name='packages_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='packages_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='qnty_ordered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallcovering',
            name='qnty_received',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
