# Generated by Django 4.1.3 on 2022-12-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0138_wallcovering_packages_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallcovering',
            name='estimated_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='wallcovering',
            name='estimated_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
