# Generated by Django 4.1.3 on 2022-12-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0139_alter_wallcovering_estimated_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Ordered'),
        ),
        migrations.AlterField(
            model_name='outgoingitem',
            name='quantity_sent',
            field=models.IntegerField(default=0, verbose_name='Packages Sent to Job'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_packages', to='console.wallcoveringdelivery'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='quantity_received',
            field=models.IntegerField(default=0, verbose_name='Packages Received'),
        ),
        migrations.AlterField(
            model_name='receiveditems',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_receiveditems2', to='console.orderitems'),
        ),
        migrations.AlterField(
            model_name='receiveditems',
            name='wallcovering_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_receiveditems1', to='console.wallcoveringdelivery'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wallcoveringdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_wallcoveringdelivery', to='console.orders'),
        ),
    ]
