# Generated by Django 4.1.3 on 2022-12-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0140_alter_orderitems_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='day_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='month_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='week_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
