# Generated by Django 4.1.3 on 2022-12-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0141_rentals_day_price_rentals_month_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
