# Generated by Django 4.1.3 on 2022-12-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0142_rentals_is_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventorytype')),
            ],
        ),
    ]
