# Generated by Django 4.1.3 on 2022-12-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0143_inventoryitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitems',
            old_name='item',
            new_name='type',
        ),
    ]
