# Generated by Django 4.1.3 on 2022-12-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0144_rename_item_inventoryitems_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItems4',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventorytype')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItems3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventorytype')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItems2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventorytype')),
            ],
        ),
    ]
