# Generated by Django 4.1.3 on 2022-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0145_inventoryitems4_inventoryitems3_inventoryitems2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
