# Generated by Django 4.1.3 on 2022-12-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0147_alter_inventorytype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitems2',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventoryitems'),
        ),
        migrations.AlterField(
            model_name='inventoryitems3',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventoryitems2'),
        ),
        migrations.AlterField(
            model_name='inventoryitems4',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.inventoryitems3'),
        ),
    ]
