# Generated by Django 4.1.3 on 2023-01-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0149_remove_inventory_vendor_inventory_service_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
            ],
        ),
    ]
