# Generated by Django 4.1.3 on 2023-01-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0150_batchinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinventory',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='batchinventory',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch1', to='console.jobs'),
        ),
    ]
