# Generated by Django 4.1.3 on 2023-01-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0151_batchinventory_current_inventory_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallcoveringdelivery',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
