# Generated by Django 4.1.3 on 2023-01-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0152_wallcoveringdelivery_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallcovering',
            name='packages_received',
        ),
        migrations.RemoveField(
            model_name='wallcovering',
            name='packages_sent',
        ),
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='po_number',
            field=models.CharField(max_length=25),
        ),
    ]
