# Generated by Django 4.1.3 on 2023-01-17 14:11

import console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0154_jobs_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotes',
            name='type',
            field=models.CharField(max_length=50, null=True, validators=[console.models.validate_job_notes]),
        ),
    ]
