# Generated by Django 4.1.3 on 2023-01-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0156_jobs_start_date_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
