# Generated by Django 4.1.3 on 2023-01-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0158_alter_changeorders_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientJobRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.clientemployees')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
            ],
        ),
    ]
