# Generated by Django 4.1.3 on 2023-01-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0159_clientjobroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientjobroles',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='console.clientemployees'),
        ),
    ]
