# Generated by Django 4.1.3 on 2023-01-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0160_alter_clientjobroles_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='full_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
