# Generated by Django 4.1.3 on 2023-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0161_changeorders_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='is_approved_to_bill',
            field=models.BooleanField(default=False),
        ),
    ]
