# Generated by Django 4.1.3 on 2023-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0162_changeorders_is_approved_to_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractors',
            name='insurance_expire_date',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcontractors',
            name='is_signed_labor_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
