# Generated by Django 4.1.3 on 2023-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0163_subcontractors_insurance_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractors',
            name='insurance_expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
