# Generated by Django 4.1.3 on 2023-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0164_alter_subcontractors_insurance_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractors',
            name='contact',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
