# Generated by Django 4.1.3 on 2023-01-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0165_subcontractors_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontractors',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
