# Generated by Django 4.1.3 on 2023-01-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0166_alter_subcontractors_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractors',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
