# Generated by Django 4.1.3 on 2023-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0167_subcontractors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontracts',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
