# Generated by Django 4.1.3 on 2023-01-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0169_rename_subcontractor_subcontractors_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontracts',
            name='description',
        ),
        migrations.AddField(
            model_name='subcontracts',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
