# Generated by Django 4.1.3 on 2023-01-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0170_remove_subcontracts_description_subcontracts_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pay_app_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='subcontracts',
            name='is_retainage',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubcontractorInvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='console.subcontractorinvoice')),
                ('sov_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item2', to='console.subcontractitems')),
            ],
        ),
        migrations.AddField(
            model_name='subcontractorinvoice',
            name='subcontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='console.subcontracts'),
        ),
    ]
