# Generated by Django 4.1.3 on 2023-01-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0171_subcontractorinvoice_subcontracts_is_retainage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorinvoice',
            name='retainage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subcontracts',
            name='retainage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
