# Generated by Django 4.1.3 on 2023-01-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0172_subcontractorinvoice_retainage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorinvoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
