# Generated by Django 4.1.3 on 2023-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0173_subcontractorinvoice_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorinvoice',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
