# Generated by Django 4.1.3 on 2023-01-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0174_subcontractorinvoice_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractorinvoice',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
