# Generated by Django 4.1.3 on 2023-01-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0175_subcontractorinvoice_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_notes2', to='console.subcontractorinvoice')),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_notes', to='console.subcontracts')),
            ],
        ),
    ]
