# Generated by Django 4.1.3 on 2023-02-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0177_tmlist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmlist',
            name='week_ending',
            field=models.DateField(null=True),
        ),
    ]
