# Generated by Django 4.1.3 on 2023-02-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0178_tmlist_week_ending'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmlist',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
