# Generated by Django 4.1.3 on 2023-02-08 12:10

import console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0180_ewticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewticket',
            name='category',
            field=models.CharField(max_length=50, null=True, validators=[console.models.validate_tm_category]),
        ),
    ]
