# Generated by Django 4.1.3 on 2023-02-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0181_alter_ewticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWT',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_ending', models.DateField()),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.changeorders')),
            ],
        ),
    ]
