# Generated by Django 4.1.3 on 2023-02-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0182_ewt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewticket',
            name='EWT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='console.ewt'),
            preserve_default=False,
        ),
    ]
