# Generated by Django 4.1.3 on 2023-02-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0183_ewticket_ewt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewticket',
            name='change_order',
        ),
        migrations.RemoveField(
            model_name='ewticket',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ewticket',
            name='week_ending',
        ),
    ]
