# Generated by Django 4.1.3 on 2023-02-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0185_ewt_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='client_Pm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PM', to='console.clientemployees'),
        ),
    ]
