# Generated by Django 4.1.3 on 2023-02-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0187_alter_clientemployees_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployees',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='clientemployees',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
