# Generated by Django 4.1.3 on 2023-02-09 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0188_alter_clientemployees_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRecipients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.clientemployees')),
            ],
        ),
    ]
