# Generated by Django 4.1.3 on 2023-02-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0189_temprecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprecipients',
            name='changeorder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='console.changeorders'),
            preserve_default=False,
        ),
    ]
