# Generated by Django 4.1.3 on 2023-02-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0192_alter_clientemployees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployees',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
