# Generated by Django 4.1.3 on 2023-02-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0193_alter_clientemployees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='sent_to',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
