# Generated by Django 4.1.3 on 2023-02-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0194_changeorders_sent_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCharges',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.tmpricesmaster')),
            ],
        ),
    ]
