# Generated by Django 4.1.3 on 2023-02-14 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0195_jobcharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmlist',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.ewticket'),
        ),
    ]
