# Generated by Django 4.1.3 on 2023-02-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0196_alter_tmlist_change_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmlist',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tmlist',
            name='week_ending',
        ),
        migrations.AlterField(
            model_name='tmlist',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
