# Generated by Django 4.1.3 on 2023-02-14 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0197_remove_tmlist_item_remove_tmlist_week_ending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmlist',
            name='notes',
        ),
        migrations.CreateModel(
            name='TMProposal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.changeorders')),
            ],
        ),
    ]
