# Generated by Django 4.1.3 on 2023-02-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0199_tmlist_proposal_tmproposal_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmlist',
            name='category2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
