# Generated by Django 4.1.3 on 2023-02-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0200_tmlist_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmproposal',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.ewt'),
        ),
    ]
