# Generated by Django 4.1.3 on 2023-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0201_alter_tmproposal_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
