# Generated by Django 4.1.3 on 2023-02-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0202_alter_changeorders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorders',
            name='gc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
