# Generated by Django 4.1.3 on 2023-02-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0203_alter_changeorders_gc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ewticket',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ewtmaster', to='console.tmpricesmaster'),
        ),
    ]
