# Generated by Django 4.1.3 on 2023-03-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0204_alter_ewticket_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalitems',
            name='wallcovering_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.wallcovering'),
        ),
    ]
