# Generated by Django 4.1.3 on 2023-03-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0205_alter_submittalitems_wallcovering_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittalNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=40, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('submittal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.submittals')),
            ],
        ),
    ]
