# Generated by Django 4.1.3 on 2023-03-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0207_submittalitems_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittals',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
