# Generated by Django 4.1.3 on 2023-03-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0209_employeelevels_employees_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Metric_Levels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employeelevels')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.metrics')),
            ],
        ),
        migrations.CreateModel(
            name='Metric_Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.metrics')),
            ],
        ),
    ]
