# Generated by Django 4.1.3 on 2023-03-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0210_metrics_metric_levels_metric_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=2000)),
                ('foreman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
            ],
        ),
        migrations.RenameModel(
            old_name='Metric_Levels',
            new_name='MetricLevels',
        ),
        migrations.RenameModel(
            old_name='Metric_Categories',
            new_name='MetricCategories',
        ),
        migrations.CreateModel(
            name='WriteUp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=2000)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Employee', to='console.employees')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Supervisor', to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='VacationApprovers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacation_date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('employee_note', models.CharField(max_length=2000)),
                ('is_approved', models.BooleanField(default=False)),
                ('request_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='MetricAssessment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=2000)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Metric_Assessment_Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.metricassessment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.metriccategories')),
                ('daily_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedVacations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_sent', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approver_notes', models.CharField(max_length=2000)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.vacation')),
            ],
        ),
    ]
