# Generated by Django 4.1.3 on 2023-03-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0211_dailyreports_rename_metric_levels_metriclevels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=2000)),
                ('max_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('note', models.CharField(max_length=2000)),
                ('is_closed', models.BooleanField(default=False)),
                ('apprentice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apprentice', to='console.employees')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor', to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('details', models.CharField(max_length=2000)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class1', to='console.metrics')),
                ('assessment_category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class2', to='console.metrics')),
            ],
        ),
        migrations.CreateModel(
            name='SuperWeeklyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('completed', models.CharField(max_length=2000)),
                ('remaining', models.CharField(max_length=2000)),
                ('issues', models.CharField(max_length=2000)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
                ('superintendent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='SuperReportEmployees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.superweeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionValues',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('unit2', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.productioncategories')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('unit2', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=2000)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.productionvalues')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('metric_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.metricassessment')),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.mentorship')),
            ],
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=2000)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='console.employees')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='console.employees')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportEmployees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports')),
            ],
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.jobs')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.trainingtopic')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=2000)),
                ('class_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.classoccurrence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
    ]
