# Generated by Django 4.1.3 on 2023-03-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0214_certificationcategories_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
