# Generated by Django 4.1.3 on 2023-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0218_alter_metricassessment_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTitles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
