# Generated by Django 4.1.3 on 2023-03-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0219_employeetitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='title',
        ),
        migrations.AddField(
            model_name='employees',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='console.employeetitles'),
        ),
    ]
