# Generated by Django 4.1.3 on 2023-03-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0221_alter_employees_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metric_Assessment_Item',
            new_name='MetricAssessmentItem',
        ),
    ]
