# Generated by Django 4.1.3 on 2023-03-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0222_rename_metric_assessment_item_metricassessmentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricassessmentitem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.metricassessment'),
        ),
        migrations.AlterField(
            model_name='metricassessmentitem',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports'),
        ),
        migrations.AlterField(
            model_name='metricassessmentitem',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
