# Generated by Django 4.1.3 on 2023-03-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0223_alter_metricassessmentitem_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricassessmentitem',
            name='daily_report',
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.metricassessment')),
                ('daily_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
            ],
        ),
        migrations.AlterField(
            model_name='metricassessmentitem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.employeereview'),
        ),
    ]
