# Generated by Django 4.1.3 on 2023-03-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0224_remove_metricassessmentitem_daily_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreports',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
