# Generated by Django 4.1.3 on 2023-03-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0225_alter_dailyreports_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionvalues',
            name='description2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
