# Generated by Django 4.1.3 on 2023-03-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0230_productioncategory1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCategory2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCategory3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
