# Generated by Django 4.1.3 on 2023-03-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0231_productioncategory2_productioncategory3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory1')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory2')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory3')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.productiontask')),
            ],
        ),
    ]
