# Generated by Django 4.1.3 on 2023-03-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0232_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='team_note',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionitems',
            name='unit3',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
