# Generated by Django 4.1.3 on 2023-03-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0233_productionitems_is_team_productionitems_team_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory1'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory2'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory3'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='console.productiontask'),
            preserve_default=False,
        ),
    ]
