# Generated by Django 4.1.3 on 2023-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0234_productionitems_category1_productionitems_category2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='description',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionitems',
            name='value3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
