# Generated by Django 4.1.3 on 2023-03-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0235_productionitems_description_productionitems_value3'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProductionItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('unit', models.CharField(max_length=20)),
                ('unit2', models.CharField(max_length=20)),
                ('unit3', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=2000)),
                ('is_team', models.BooleanField(default=False)),
                ('team_note', models.CharField(max_length=2000)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory1')),
                ('category2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory2')),
                ('category3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory3')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.employees')),
                ('metric_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.metricassessment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='console.productiontask')),
            ],
        ),
    ]
