# Generated by Django 4.1.3 on 2023-03-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0236_tempproductionitems'),
    ]

    operations = [

        migrations.AlterField(
            model_name='dailyreports',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.dailyreports'),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='metric_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.metricassessment'),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='team_note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='unit2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productionitems',
            name='unit3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
