# Generated by Django 4.1.3 on 2023-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0237_productionitems_date_tempproductionitems_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tempproductionitems',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
