# Generated by Django 4.1.3 on 2023-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0238_productionitems_date_tempproductionitems_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncategory1',
            name='unit1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productioncategory1',
            name='unit2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productioncategory1',
            name='unit3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
