# Generated by Django 4.1.3 on 2023-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0239_productioncategory1_unit1_productioncategory1_unit2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item1', models.CharField(max_length=200)),
                ('item2', models.CharField(blank=True, max_length=200, null=True)),
                ('item3', models.CharField(blank=True, max_length=200, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('unit1', models.CharField(blank=True, max_length=200, null=True)),
                ('unit2', models.CharField(blank=True, max_length=200, null=True)),
                ('unit3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
