# Generated by Django 4.1.3 on 2023-03-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0241_productionitems_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionitems',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productionitems',
            name='task',
        ),
    ]
