# Generated by Django 4.1.3 on 2023-03-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0242_remove_productionitems_category1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.productioncategory'),
        ),
    ]
