# Generated by Django 4.1.3 on 2023-03-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0243_productionitems_description_productionitems_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoccurrence',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classoccurrence',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='classoccurrence',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classoccurrence',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='classoccurrence',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.trainingtopic'),
        ),
    ]
