# Generated by Django 4.1.3 on 2023-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0244_classoccurrence_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendees',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
