# Generated by Django 4.1.3 on 2023-03-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0245_alter_classattendees_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='classoccurrence',
            name='teacher2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classoccurrence',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.employees'),
        ),
    ]
