# Generated by Django 4.1.3 on 2023-03-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0246_classoccurrence_teacher2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtopic',
            name='assessment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class1', to='console.metrics'),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='assessment_category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class2', to='console.metrics'),
        ),
    ]
