# Generated by Django 4.1.3 on 2023-03-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0247_alter_trainingtopic_assessment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendees',
            name='student2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classattendees',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.employees'),
        ),
    ]
