# Generated by Django 4.1.3 on 2023-03-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0250_examscore_exam2_examscore_student2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscore',
            name='custom_score_max',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
