# Generated by Django 4.1.3 on 2023-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0251_examscore_custom_score_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorship',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
