# Generated by Django 4.1.3 on 2023-03-28 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0252_mentorship_end_date_alter_mentorship_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='date_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='certifications',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
