# Generated by Django 4.1.3 on 2023-03-29 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0253_alter_certifications_date_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('certification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='console.certifications')),
            ],
        ),
    ]
