# Generated by Django 4.1.3 on 2023-04-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0254_certificationnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certifications',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
    ]
