# Generated by Django 4.1.3 on 2023-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0255_certifications_action_certifications_action_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationActionRequired',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
