# Generated by Django 4.1.3 on 2023-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0256_certificationactionrequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
