# Generated by Django 4.1.3 on 2023-04-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0257_writeup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='console.jobs'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='note',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
