# Generated by Django 4.1.3 on 2023-04-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0258_alter_writeup_job_alter_writeup_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteUpDefaults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
