# Generated by Django 4.1.3 on 2023-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0259_writeupdefaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitems',
            name='team_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
