# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedVacations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_sent', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approver_notes', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationActionRequired',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificationNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_expires', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student2', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassOccurrence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('teacher2', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportEmployees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLevels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_number', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('employer', models.CharField(max_length=100)),
                ('pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTitles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=2000)),
                ('max_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exam2', models.CharField(blank=True, max_length=200, null=True)),
                ('student2', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher2', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('custom_score_max', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinEntryDate', models.DateTimeField(auto_now_add=True)),
                ('pin', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricAssessment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricAssessmentItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MetricLevels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item1', models.CharField(max_length=200)),
                ('item2', models.CharField(blank=True, max_length=200, null=True)),
                ('item3', models.CharField(blank=True, max_length=200, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('unit1', models.CharField(blank=True, max_length=200, null=True)),
                ('unit2', models.CharField(blank=True, max_length=200, null=True)),
                ('unit3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value1', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('value3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('unit2', models.CharField(blank=True, max_length=20, null=True)),
                ('unit3', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_team', models.BooleanField(default=False)),
                ('team_note', models.CharField(blank=True, max_length=2000, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('team_members', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('team_number', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperReportEmployees',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuperWeeklyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('completed', models.CharField(max_length=2000)),
                ('remaining', models.CharField(max_length=2000)),
                ('issues', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('details', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacation_date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('employee_note', models.CharField(max_length=2000)),
                ('is_approved', models.BooleanField(default=False)),
                ('request_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VacationApprovers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WriteUpDefaults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WriteUp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Employee', to='employees.employees')),
            ],
        ),
    ]
