# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='writeup',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Supervisor', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='vacationapprovers',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='assessment_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class1', to='employees.metrics'),
        ),
        migrations.AddField(
            model_name='trainingtopic',
            name='assessment_category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class2', to='employees.metrics'),
        ),
        migrations.AddField(
            model_name='superweeklyreport',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='superweeklyreport',
            name='superintendent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='superreportemployees',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='superreportemployees',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.superweeklyreport'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.dailyreports'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='metric_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.metricassessment'),
        ),
        migrations.AddField(
            model_name='productionitems',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.productioncategory'),
        ),
        migrations.AddField(
            model_name='metriclevels',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employeelevels'),
        ),
        migrations.AddField(
            model_name='metriclevels',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.metrics'),
        ),
        migrations.AddField(
            model_name='metriccategories',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.metrics'),
        ),
        migrations.AddField(
            model_name='metricassessmentitem',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employeereview'),
        ),
        migrations.AddField(
            model_name='metricassessmentitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.metriccategories'),
        ),
        migrations.AddField(
            model_name='metricassessmentitem',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='metricassessment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='metricassessment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='mentorshipnotes',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.mentorship'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='apprentice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apprentice', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mentor', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='gpuseraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examscore',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.exam'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='examscore',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='employees.employees'),
        ),
        migrations.AddField(
            model_name='employees',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employeetitles'),
        ),
        migrations.AddField(
            model_name='employees',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employeelevels'),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeereview',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.metricassessment'),
        ),
        migrations.AddField(
            model_name='employeereview',
            name='daily_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.dailyreports'),
        ),
        migrations.AddField(
            model_name='employeereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='dailyreports',
            name='foreman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='dailyreports',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='dailyreportemployees',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='dailyreportemployees',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.dailyreports'),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='classoccurrence',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.trainingtopic'),
        ),
        migrations.AddField(
            model_name='classattendees',
            name='class_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.classoccurrence'),
        ),
        migrations.AddField(
            model_name='classattendees',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.certificationcategories'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='certifications',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='certificationnotes',
            name='certification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.certifications'),
        ),
        migrations.AddField(
            model_name='approvedvacations',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='approvedvacations',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.vacation'),
        ),
    ]
