# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='job_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchased_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory1', to='equipment.vendors'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='service_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory2', to='equipment.vendors'),
        ),
        migrations.AddField(
            model_name='batchinventory',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch1', to='jobs.jobs'),
        ),
    ]
