# Generated by Django 3.2.20 on 2023-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
