# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=250, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=250, null=True)),
                ('on_rent_date', models.DateField(blank=True, null=True)),
                ('off_rent_date', models.DateField(blank=True, null=True)),
                ('off_rent_number', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('day_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('week_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('month_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.vendors')),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
            ],
        ),
    ]
