# Generated by Django 3.2.20 on 2023-10-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.vendorcontact'),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='RentalNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.rentals')),
            ],
        ),
    ]
