# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallcovering', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('SOV_description', models.CharField(max_length=250, null=True)),
                ('SOV_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SOV_is_lump_sum', models.BooleanField(default=False)),
                ('SOV_unit', models.CharField(max_length=50, null=True)),
                ('SOV_total_ordered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SOV_total_authorized', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SOV_quantity_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SOV_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=2050, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractorInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pay_app_number', models.IntegerField(default=0)),
                ('retainage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=250, null=True)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('insurance_expire_date', models.DateField(blank=True, null=True)),
                ('is_signed_labor_agreement', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontracts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=250, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_retainage', models.BooleanField(default=True)),
                ('retainage_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract', to='subcontractors.subcontractors')),
            ],
        ),
        migrations.CreateModel(
            name='SubcontractorInvoiceItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item', to='subcontractors.subcontractorinvoice')),
                ('sov_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_item2', to='subcontractors.subcontractitems')),
            ],
        ),
        migrations.AddField(
            model_name='subcontractorinvoice',
            name='subcontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='subcontractors.subcontracts'),
        ),
        migrations.CreateModel(
            name='SubcontractNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_notes2', to='subcontractors.subcontractorinvoice')),
                ('subcontract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontract_notes', to='subcontractors.subcontracts')),
            ],
        ),
        migrations.AddField(
            model_name='subcontractitems',
            name='subcontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subcontractors.subcontracts'),
        ),
        migrations.AddField(
            model_name='subcontractitems',
            name='wallcovering_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallcovering.wallcovering'),
        ),
    ]
