# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Ordered')),
                ('unit', models.CharField(max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_description', models.CharField(max_length=100, null=True)),
                ('item_notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_satisfied', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitems2', to='jobs.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Wallcovering',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, null=True)),
                ('pattern', models.CharField(max_length=2000, null=True)),
                ('estimated_quantity', models.IntegerField(blank=True, default=0)),
                ('estimated_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('cut_charge', models.CharField(blank=True, max_length=1000, null=True)),
                ('roll_width', models.CharField(blank=True, max_length=50, null=True)),
                ('vertical_repeat', models.CharField(blank=True, max_length=50, null=True)),
                ('is_random_reverse', models.BooleanField(default=False)),
                ('is_repeat', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('qnty_ordered', models.IntegerField(blank=True, null=True)),
                ('qnty_received', models.IntegerField(blank=True, null=True)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='WallcoveringPricing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quote_date', models.DateField()),
                ('min_yards', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
                ('wallcovering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallcovering.wallcovering')),
            ],
        ),
        migrations.CreateModel(
            name='WallcoveringDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_wallcoveringdelivery', to='jobs.orders')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_receiveditems2', to='wallcovering.orderitems')),
                ('wallcovering_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_receiveditems1', to='wallcovering.wallcoveringdelivery')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200, null=True)),
                ('contents', models.CharField(max_length=2000, null=True)),
                ('quantity_received', models.IntegerField(default=0, verbose_name='Packages Received')),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foreign_packages', to='wallcovering.wallcoveringdelivery')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingWallcovering',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivered_by', models.CharField(max_length=200, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('job_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('quantity_sent', models.IntegerField(default=0, verbose_name='Packages Sent to Job')),
                ('outgoing_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallcovering.outgoingwallcovering')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallcovering.packages')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='wallcovering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderitems1', to='wallcovering.wallcovering'),
        ),
    ]
