from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(TemporaryPassword)
admin.site.register(Employees)
admin.site.register(Metrics)
admin.site.register(MetricCategories)
admin.site.register(MetricLevels)
admin.site.register(MetricAssessment)
admin.site.register(DailyReports)
admin.site.register(MetricAssessmentItem)
admin.site.register(WriteUp)
admin.site.register(Vacation)
admin.site.register(VacationApprovers)
admin.site.register(ApprovedVacations)
admin.site.register(DailyReportEmployees)
admin.site.register(Mentorship)
admin.site.register(MentorshipNotes)
admin.site.register(CertificationCategories)
admin.site.register(Certifications)
admin.site.register(EmployeeLevels)
admin.site.register(EmployeeTitles)
admin.site.register(EmployeeReview)
admin.site.register(TrainingTopic)
admin.site.register(ClassOccurrence)
admin.site.register(ClassAttendees)
admin.site.register(Exam)
admin.site.register(ExamScore)
admin.site.register(ProductionCategory)
admin.site.register(CertificationActionRequired)
admin.site.register(WriteUpDefaults)
admin.site.register(ProductionItems)
admin.site.register(SuperWeeklyReport)
admin.site.register(SuperReportEmployees)
admin.site.register(Employers)