from django.urls import path

from . import views


urlpatterns = [
path("employees_home", views.employees_home, name='employees_home'),
path("employees_page/<id>", views.employees_page, name='employees_page'),
path("training", views.training, name='training'),
path("my_page", views.my_page, name='my_page'),
path("certifications/<id>", views.certifications, name='certifications'),
path("new_certification", views.new_certification, name='new_certification'),
path("add_new_employee", views.add_new_employee, name='add_new_employee'),
path("assessments/<id>", views.assessments, name='assessments'),
path("production_reports/<id>", views.production_reports, name='production_reports'),
path("classes/<id>", views.classes, name='classes'),
path("new_class", views.new_class, name='new_class'),
path("exams/<id>", views.exams, name='exams'),
path("new_exam", views.new_exam, name='new_exam'),
path("mentorships/<id>", views.mentorships, name='mentorships'),
path("new_mentorship", views.new_mentorship, name='new_mentorship'),
path("new_assessment/<id>", views.new_assessment, name='new_assessment'),
path("new_production_report/<jobnumber>", views.new_production_report, name='new_production_report'),
path("write_ups/<id>", views.write_ups, name='write_ups'),
path("write_ups_new", views.write_ups_new, name='write_ups_new'),
path("employee_notes/<employee>", views.employee_notes, name='employee_notes'),
path("daily_reports/<id>", views.daily_reports, name='daily_reports'),
path('safety_home', views.safety_home, name='safety_home'),
path('toolbox_talks_master', views.toolbox_talks_master, name='toolbox_talks_master'),
path('scheduled_toolbox_talks', views.scheduled_toolbox_talks, name='scheduled_toolbox_talks'),
path('respirator_clearance_section1', views.respirator_clearance_section1, name='respirator_clearance_section1'),
path('respirator_clearance_section2', views.respirator_clearance_section2, name='respirator_clearance_section2'),
path('respirator_clearance_section3', views.respirator_clearance_section3, name='respirator_clearance_section3'),
path('respirator_clearance_section4', views.respirator_clearance_section4, name='respirator_clearance_section4'),
path('respirator_clearance_section5', views.respirator_clearance_section5, name='respirator_clearance_section5'),
path('respirator_clearance_section6', views.respirator_clearance_section6, name='respirator_clearance_section6'),
path('respirator_clearance_section0', views.respirator_clearance_section0, name='respirator_clearance_section0'),
path('respirator_clearance_base', views.respirator_clearance_base, name='respirator_clearance_base'),
path('respirator_clearance_completed/<respirator_id>', views.respirator_clearance_completed, name='respirator_clearance_completed'),
path('toolbox_talks_by_employee', views.toolbox_talks_by_employee, name='toolbox_talks_by_employee'),
path("view_respirator_certification/<id>", views.view_respirator_certification, name='view_respirator_certification'),
path("delete_employee/<id>", views.delete_employee, name='delete_employee'),
path("upload_employees", views.upload_employees, name="upload_employees"),
path("toolbox_file/<int:scheduled_id>/<str:language>/",
     views.toolbox_file,
     name="toolbox_file"),
]