# Generated by Django 3.2.20 on 2023-09-29 13:09

import changeorder.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrderNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cop_number', models.IntegerField(default=0)),
                ('is_t_and_m', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=700, null=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('gc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_work_complete', models.BooleanField(default=False)),
                ('is_ticket_signed', models.BooleanField(default=False)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('date_week_ending', models.DateField(blank=True, null=True)),
                ('ticket_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('materials_used', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('full_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_approved_to_bill', models.BooleanField(default=False)),
                ('sent_to', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientJobRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EWT',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('week_ending', models.DateField()),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('completed_by', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EWTicket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, null=True, validators=[changeorder.models.validate_tm_category])),
                ('monday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tuesday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('wednesday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('thursday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('friday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('saturday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sunday', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ot', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('units', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMPricesMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, validators=[changeorder.models.validate_tm_category])),
                ('item', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='TMProposal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(max_length=2000, null=True)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.changeorders')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.ewt')),
            ],
        ),
        migrations.CreateModel(
            name='TMList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('units', models.CharField(max_length=10)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.CharField(max_length=50, validators=[changeorder.models.validate_tm_category])),
                ('category2', models.CharField(max_length=200)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.changeorders')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.tmproposal')),
            ],
        ),
        migrations.CreateModel(
            name='TempRecipients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('changeorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.changeorders')),
            ],
        ),
    ]
