# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('jobs', '0001_initial'),
        ('changeorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprecipients',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.clientemployees'),
        ),
        migrations.AddField(
            model_name='ewticket',
            name='EWT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.ewt'),
        ),
        migrations.AddField(
            model_name='ewticket',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employees'),
        ),
        migrations.AddField(
            model_name='ewticket',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ewtmaster', to='changeorder.tmpricesmaster'),
        ),
        migrations.AddField(
            model_name='ewt',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.changeorders'),
        ),
        migrations.AddField(
            model_name='clientjobroles',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='jobs.clientemployees'),
        ),
        migrations.AddField(
            model_name='clientjobroles',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='changeorders',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='changeordernotes',
            name='cop_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.changeorders'),
        ),
    ]
