# Generated by Django 3.2.20 on 2023-10-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeorder', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=50)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='changeorder.changeorders')),
            ],
        ),
    ]
