# Generated by Django 3.2.20 on 2023-10-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeorder', '0003_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='change_order',
        ),
        migrations.AddField(
            model_name='signature',
            name='change_order_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
