# Generated by Django 3.2.20 on 2023-10-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeorder', '0005_auto_20231016_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
