"""
Django settings for trinity project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env", override=True)
#load_dotenv()  # THIS loads the .env file

# clockshark integration
ZAPIER_SECRET = os.getenv("ZAPIER_SECRET")
ZAPIER_CREATE_JOB_WEBHOOK = os.getenv("ZAPIER_CREATE_JOB_WEBHOOK")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.168.120', '98.174.216.233', '184.183.68.156']
ALLOWED_HOSTS = ["*"]
# Application definition

INSTALLED_APPS = [
    'django.contrib.humanize',
    'django_tables2',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'console.apps.ConsoleConfig',
    'jobs',
    'changeorder',
    'equipment',
    'employees',
    'rentals',
    'subcontractors',
    'wallcovering',
    'superintendent',
    'submittals',
    'accounts',
    'autos',
]

# django.setup()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trinity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'submittals/templates', 'console/templates', 'templates', 'superintendent/templates',
                 'templates/bootstrap', 'changeorder/templates', 'equipment/templates', 'employees/templates',
                 'jobs/templates', 'rentals/templates', 'subcontractors/templates', 'wallcovering/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trinity.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Password4880',
        'HOST': 'localhost'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = "US/Eastern"
USE_TZ = True
DATETIME_FORMAT = "m/d/Y g:i A"
TIME_FORMAT = "g:i A"
USE_I18N = True
DATETIME_INPUT_FORMATS = [
    "%m/%d/%Y %I:%M %p",  # 12-hour with AM/PM
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

STATICFILES_DIR = [
BASE_DIR / "static"
]
#STATICFILES_DIR =['/jobs/static/jobs/project_styles.css']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# For Emails
DEFAULT_FROM_EMAIL = 'joe@gerloffpainting.com'
EMAIL_HOST = '192.168.168.19'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'joe@gerloffpainting.com'
EMAIL_USE_TLS = False
EMAIL_HOST_PASSWORD = 'Password$*80'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
