from django.contrib import admin

from .models import *
# Register your models here.
admin.site.register(WallcoveringDelivery)
admin.site.register(Wallcovering)
admin.site.register(Vendors)
admin.site.register(VendorContact)
admin.site.register(VendorCategory)
admin.site.register(TMPricesMaster)
admin.site.register(TMList)
admin.site.register(Submittals)
admin.site.register(SubmittalItems)
admin.site.register(Subcontracts)
admin.site.register(Subcontractors)
admin.site.register(SubcontractItems)
admin.site.register(StorageLocationType)
admin.site.register(Rentals)
admin.site.register(Plans)
admin.site.register(Packages)
admin.site.register(OutgoingWallcovering)
admin.site.register(OutgoingItem)
admin.site.register(Orders)
admin.site.register(OrderItems)
admin.site.register(Jobs)
admin.site.register(JobNumbers)
admin.site.register(JobNotes)
admin.site.register(InventoryType)
admin.site.register(Inventory)
admin.site.register(InventoryNotes)
admin.site.register(InventoryItems)
admin.site.register(InventoryItems2)
admin.site.register(InventoryItems3)
admin.site.register(InventoryItems4)
admin.site.register(Estimates)
admin.site.register(Employees)
admin.site.register(Clients)
admin.site.register(ClientEmployees)
admin.site.register(Checklist)
admin.site.register(ChangeOrders)
admin.site.register(ReceivedItems)
admin.site.register(WallcoveringPricing)
admin.site.register(SubcontractorInvoice)
admin.site.register(SubcontractorInvoiceItem)
admin.site.register(SubcontractNotes)
admin.site.register(PainterHours)
admin.site.register(EWTicket)
admin.site.register(EWT)