# Generated by Django 3.2.20 on 2023-09-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallcovering', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submittals',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('submittal_number', models.IntegerField(default=0)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobs')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalNotes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.CharField(max_length=40, null=True)),
                ('note', models.CharField(max_length=2000, null=True)),
                ('submittal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submittals.submittals')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('submittal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submittals.submittals')),
                ('wallcovering_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wallcovering.wallcovering')),
            ],
        ),
    ]
